local job = require("dotnet-cli.job")

describe("job", function()
  describe("run_sync", function()
    it("returns lines and ok status for successful commands", function()
      local lines, ok = job.run_sync({ "echo", "hello" })
      assert.is_true(ok)
      assert.is_table(lines)
      assert.are.equal("hello", lines[1])
    end)

    it("returns lines and false for failed commands", function()
      local lines, ok = job.run_sync({ "false" })
      assert.is_false(ok)
      assert.is_table(lines)
    end)

    it("handles string commands", function()
      local lines, ok = job.run_sync("echo world")
      assert.is_true(ok)
      assert.are.equal("world", lines[1])
    end)
  end)
end)
